name: Build

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        shell: bash
        run: |
          sed -i 36,48d ./scripts/setup.bash ./scripts/setup.bash
          sed -i 35a\\"rosdep update && rosdep install --from-paths ./ --ignore-src -r -y" ./scripts/setup.bash
          . ./scripts/setup.bash

      - name: Build
        shell: bash
        run: . /opt/ros/humble/setup.bash && colcon build
