name: Build

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: . ./scripts/setup.bash

      - name: Build
        shell: bash
        run: . /opt/ros/humble/setup.bash && colcon build
